- name: SET ip_forward
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: SET ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: start firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

#ansible-galaxy collection install ansible.posix

- name: forward ports
  shell: firewall-cmd --permanent --zone=public --add-masquerade

- name: forward ports http
  shell: firewall-cmd --permanent --add-forward-port=port=80:proto=tcp:toport=80:toaddr=192.168.10.5

- name: forward ports haproxy web
  shell: firewall-cmd --permanent --add-forward-port=port=10001:proto=tcp:toport=10001:toaddr=192.168.10.5

- name: forward ports haproxy db
  shell: firewall-cmd --permanent --add-forward-port=port=7000:proto=tcp:toport=7000:toaddr=192.168.10.8
  
- name: restart
  shell: firewall-cmd --reload 