# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.10.10"
    master.vm.hostname = "master"
  end
  config.vm.define "slave" do |slave|
    slave.vm.network "private_network", ip: "192.168.10.20"
    slave.vm.hostname = "slave"
  end
  config.vm.define "backup" do |backup|
    backup.vm.network "private_network", ip: "192.168.10.30"
    backup.vm.hostname = "backup"
  end


#   config.vm.provision "ansible" do |ansible|
#     #ansible.verbose = "vvv"
#     ansible.playbook = "provisioning/playbook.yml"
#     ansible.become = "true"
#   end

end