- name: Config inetRouter
  template:
    src: ifcfg-bond0-ir.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-bond0
  when: ansible_hostname == 'inetRouter'
  notify:
    - restart network

- name: Config centralRouter
  template:
    src: ifcfg-bond0-cr.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-bond0
  when: ansible_hostname == 'centralRouter'
  notify:
    - restart network

- name: Add configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: 'ifcfg-eth1.j2', dest: '/etc/sysconfig/network-scripts/ifcfg-eth1'}
    - {src: 'ifcfg-eth2.j2', dest: '/etc/sysconfig/network-scripts/ifcfg-eth2'}
  notify:
    - restart network