---
# tasks file for logclient
- name: Install packages
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - systemd-journal-gateway
    - libselinux-python3
    - libsemanage-python3

- name: Copy template journal-upload.conf
  template:
    src: journal-upload.conf.j2
    dest: /etc/systemd/journal-upload.conf

- name: Selinux policy
#  shell: setsebool -P nis_enabled 1
  seboolean:
    name: nis_enabled
    state: yes
    persistent: yes
    
- name: start upload service
  systemd:
    name: systemd-journal-upload
    state: started
    enabled: yes