---
# tasks file for logclient
- name: Install  systemd-journal-gateway
  yum:
    name: systemd-journal-gateway
    state: latest

- name: Copy template journal-upload.conf
  template:
    src: journal-upload.conf.j2
    dest: /etc/systemd/journal-upload.conf

- name: Selinux policy
  shell: setsebool -P nis_enabled 1

- name: start upload service
  systemd:
    name: systemd-journal-upload
    state: started
    enabled: yes