all:
  children:
    vlan:
    bonding:

bonding:
  hosts:
    inetRouter:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_private_key_file: .vagrant/machines/inetRouter/virtualbox/private_key

    centralRouter:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_ssh_private_key_file: .vagrant/machines/centralRouter/virtualbox/private_key

vlan:
  hosts:
    testServer1:
      ansible_host: 127.0.0.1
      ansible_port: 2201
      ansible_ssh_private_key_file: .vagrant/machines/testServer1/virtualbox/private_key
      vlan_id: 10.10.10.1

    testClient1:
      ansible_host: 127.0.0.1
      ansible_port: 2202
      ansible_ssh_private_key_file: .vagrant/machines/testClient1/virtualbox/private_key
      vlan_id: 10.10.10.254

    testServer2:
      ansible_host: 127.0.0.1
      ansible_port: 2203
      ansible_ssh_private_key_file: .vagrant/machines/testServer2/virtualbox/private_key
      vlan_id: 20.10.10.1

    testClient2:
      ansible_host: 127.0.0.1
      ansible_port: 2204
      ansible_ssh_private_key_file: .vagrant/machines/testClient2/virtualbox/private_key
      vlan_id: 20.10.10.254