---
- name: Prepare client tasks
  hosts: ovpn-client
  become: true
  tasks:
    - name: Copy server.conf
      template:
        src: client.conf.j2
        dest: /etc/openvpn/server.conf
      notify:
        - restart openvpn server
  handlers:
    - name: restart openvpn server
      systemd:
        name: openvpn@server
        state: restarted
        enabled: yes