  
- name: Install packages
  dnf:
    name: '{{ item }}'
    state: present
  loop:
    - network-scripts

- name: Disable NetworkManager
  systemd:
    name: NetworkManager
    enabled: no
    state: stopped
    
- name: Remove unused interface
  file:
    path: /etc/sysconfig/network-scripts/ifcfg-ens3
    state: absent

- name: Set zeroconf
  blockinfile:
    path: /etc/sysconfig/network
    block: |
      NOZEROCONF=yes
  notify: restart network
  
- name: Append a gateway
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    block: |
      GATEWAY={{ gateway }}
  notify: restart network
  
- name: Disable default route for eth0
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    block: |
      DEFROUTE=no
  notify: restart network

- name: Check if gateway set
  shell: 'ip r | grep 192.168.10.1 2> /dev/null'
  register: cmd_out
  ignore_errors: True

- name: restart network
  systemd:
    name: network
    state: restarted
  when: cmd_out.rc != 0
