- name: Append a gateway
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    block: |
      GATEWAY={{ gateway }}
  notify: restart network

- name: Check if gateway set
  shell: 'ip r | grep 192.168.10.1'
  register: cmd_out
  ignore_errors: True

- name: restart network
  systemd:
    name: NetworkManager.service
    state: restarted
  when: cmd_out.rc != 0
  
- name: restart network
  shell: nmcli networking off; nmcli networking on
  when: cmd_out.rc != 0

- name: Install packages
  dnf:
    name: '{{ item }}'
    state: present
  loop:
    - network-scripts

- name: Disable default route for eth0
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    block: |
      DEFROUTE=no
      NM_CONTROLLED=yes
  notify: restart network

