# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define "ipaserver" do |server|
    server.vm.hostname = "ipaserver"
    server.vm.network "private_network", ip: "192.168.10.1"
#     server.vm.network "forwarded_port", guest: 80, host: 80
    server.vm.network "forwarded_port", guest: 443, host: 443
    server.vm.provider "virtualbox" do |v|
      v.memory = 3072
      v.cpus = 2
    end
  end

  config.vm.define "ws1" do |ws|
    ws.vm.hostname = "ws1"
    ws.vm.network "private_network", ip: "192.168.10.2"
  end

  config.vm.define "ws2" do |ws|
    ws.vm.hostname = "ws2"
    ws.vm.network "private_network", ip: "192.168.10.3"
  end
end