---

- name: Add docker repository
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install packages
  dnf:
    name: '{{ item }}'
    state: present
  loop:
    - epel-release
    - postgresql
    - nginx
    - docker-ce
    - python3-pip

- name: Install docker dep
  pip:
    name: docker

- name: Config file for web
  file:
    path: "/etc/agency"
    state: directory

- name: Copy config web
  copy:
    src: appsettings.json
    dest: /etc/agency

- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Config file for web
  file:
    path: "/etc/agency"
    state: directory

- name: Copy config web
  copy:
    src: appsettings.json
    dest: /etc/agency

- name: SET ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    
- name: Start docker container
  docker_container:
    name: agency
    image: pitchcontrol/agency-demo:1.0
    state: started
    recreate: no
    restart: yes
    restart_policy: always
    ports:
      - "8080:80"
    volumes: '/etc/agency/:/app/settings'

- name: Selinux policy
#  shell: setsebool -P httpd_can_network_relay 1
  seboolean:
    name: httpd_can_network_relay
    state: yes
    persistent: yes

- name: copy config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: 'nginx.conf', dest: '/etc/nginx/' }
    - { src: 'agency.conf', dest: '/etc/nginx/conf.d/' }   
  notify:
    - restart nginx    