- name: Install  systemd-journal-gateway
  yum:
    name: systemd-journal-gateway
    state: latest
      
- name: Creates directory
  file:
    path: /var/log/journal/remote
    state: directory
    owner: systemd-journal-remote
    group: systemd-journal-remote
    mode: 0775

- name: config SELinux
  shell: setsebool -P use_virtualbox 1
    
- name: Copy systemdjournal-remote.service
  copy:
    src: systemdjournal-remote.service
    dest: /lib/systemd/system/systemd-journal-remote.service
  notify: restart systemd-journal-remote