- name: Install packages
  dnf:
    name: '{{ item }}'
    state: present
    disable_gpg_check: yes
  loop:
    - epel-release
    - haproxy
    - postgresql
    - libselinux-python3
    - libsemanage-python3
      
- name: Selinux policy
#  shell: setsebool -P haproxy_connect_any 1
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: copy config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: 'haproxy.cfg', dest: '/etc/haproxy/' }
    - { src: 'init.sql', dest: '/home/vagrant/' }
  notify:
    - restart haproxy

- name: start haproxy
  systemd:
    name: haproxy
    state: started
    enabled: yes        