---
- name: restart network
  systemd:
    name: NetworkManager.service
    state: restarted
    
- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted
    daemon_reload: yes  