all:
  hosts:
    ovpn-server:
      ansible_host: 192.168.10.10
      ansible_ssh_private_key_file: .vagrant/machines/server/virtualbox/private_key
      ipaddr: 10.0.0.1
      stsdev: 'tap'
      stsifconfig: '172.16.10.1 255.255.255.0'
      stsroute: '10.0.0.2 255.255.255.255 172.16.10.2'
      
    ovpn-client:
      ansible_host: 192.168.10.20
      ansible_ssh_private_key_file: .vagrant/machines/client/virtualbox/private_key
      ipaddr: 10.0.0.2
      stsdev: 'tap'
      stsremote: '192.168.10.10'
      stsifconfig: '172.16.10.2 255.255.255.0'
      stsroute: '10.0.0.1 255.255.255.255 172.16.10.1'