- hosts: webservers
  become: True
  roles:
    - webserver

- hosts: webproxy
  become: True
  roles:
    - webproxy

#- hosts: all
#  become: True
#  roles:
#    - logclient
#
#- hosts: logserver
#  become: True
#  roles:
#    - logserver

- hosts: dbs
  become: True
  roles:
    - postgresnode

- hosts: dbproxy
  become: True
  roles:
    - dbproxy