# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :webserver1 => {
      :box_name => "centos/8",
      :net => [
                 { ip: '192.168.10.2', netmask: '255.255.255.0' }
              ]
    },
    :webserver2 => {
      :box_name => "centos/8",
      :net => [
                 { ip: '192.168.10.3', netmask: '255.255.255.0' }
              ]
    }
     :logserver => {
      :box_name => "centos/8",
      :net => [
                 { ip: '192.168.10.4', netmask: '255.255.255.0' }
              ]
    }    
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
       
    end
  end
end