---
- name: Install packages
  yum:
    name:
      - tcpdump
      - traceroute
    state: present

- name: Enable 802.1q
  modprobe:
    name: 8021q
    state: present

- name: Config vlan10
  template:
    src: ifcfg-vlan10.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1.10
  when: (ansible_hostname == 'testClient1') or (ansible_hostname == 'testServer1')
  notify:
    - restart network

- name: Config vlan20
  template:
    src: ifcfg-vlan20.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1.20
  when: (ansible_hostname == 'testClient2') or (ansible_hostname == 'testServer2')
  notify:
    - restart network