home = ENV['HOME']
ENV['LC_ALL'] = 'en_US.UTF-8'

MACHINES = {
  server: {
    box_name: 'centos/7',
    ip_addr: '192.168.10.10',
  },
  client: {
    box_name: 'centos/7',
    ip_addr: '192.168.10.20',
  }
}.freeze

Vagrant.configure('2') do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network 'private_network', ip: boxconfig[:ip_addr]

      box.vm.provider :virtualbox do |vb|
        vb.customize ['modifyvm', :id, '--memory', '1024']
      end
    end
  end
  config.vm.define 'server' do |server|
  server.vm.provider :virtualbox do |vb|
    filename='./.vagrant/machines/server/virtualbox/sata24.vdi'
    unless File.exist?(filename)
      vb.customize ['createhd', '--filename', filename, '--variant', 'Fixed', '--size', 2048]
      needsController =  true
    end

    if needsController == true
      vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
      vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', filename]
    end
  end
  end
  config.vm.define 'client' do |client|
  end
end