---
- name: Install and configure
  hosts: web
  become: yes

  tasks:
    #    - name: install postgresql repo
    #      yum:
    ##        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    #        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    #        validate_certs: no
    #        state: present

    - name: Disable
      selinux:
        state: disabled

    - name: Add docker repository
      shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install packages
      dnf:
        name: '{{ item }}'
        state: present
      loop:
        - epel-release
        - postgresql-server
        - nginx
        - python3-devel
        - python3-pip
        - python3-virtualenv
        - docker-ce
        - git

    - name: Install docker dep
      pip:
        name: docker

    - name: init db
      shell: /usr/bin/postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Copy config postgres
      copy:
        src: files/{{ item }}
        dest: /var/lib/pgsql/data/
        mode: 0600
        owner: postgres
        group: postgres
      with_items:
        - pg_hba.conf
        - postgresql.conf

    - name: start postgresql
      systemd:
        name: postgresql.service
        state: restarted
        enabled: yes

    - name: create agency user
      become_user: postgres
      shell: psql postgres -c "CREATE USER agency WITH SUPERUSER PASSWORD 'P@ssw0rd'"
      ignore_errors: yes

    - name: Config file for web
      file:
        path: "/etc/agency"
        state: directory

    - name: Copy config web
      copy:
        src: files/appsettings.json
        dest: /etc/agency

    - name: start docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Start docker container
      docker_container:
        name: agency
        image: pitchcontrol/agency-demo:1.0
        state: started
        recreate: no
        ports:
          - "8080:80"
        volumes: '/etc/agency/:/app/settings'

    - name: copy config
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - { src: 'files/nginx/nginx.conf', dest: '/etc/nginx/' }
        - { src: 'files/nginx/agency.conf', dest: '/etc/nginx/conf.d/' }
        - { src: 'files/nginx/go.conf', dest: '/etc/nginx/conf.d/' }
        - { src: 'files/nginx/django.conf', dest: '/etc/nginx/conf.d/' }
      notify:
        - restart nginx

    - name: create directory go
      file:
        path: "/var/go-web"
        state: directory

    - name: copy go web
      copy:
        src: files/go-web
        dest: /var/go-web
        
    - name: set execute Go
      file:
        dest: /var/go-web/go-web
        mode: 'a+x'
          
    - name: copy go web service
      copy:
        src: files/go.service
        dest: /etc/systemd/system/

    - name: start go web
      systemd:
        name: go.service
        state: started
        enabled: yes

    - name: clone django
      git:
        repo: 'https://github.com/staybox/django-helloworld'
        dest: '/var/django'
        force: yes

    - name: Install django
      pip:
        name: django==2.2.3
        executable: pip3


    - name: set execute
      file:
        dest: '/var/django/manage.py'
        mode: 'a+x'

    - django_manage:
        command: migrate
        app_path: '/var/django'
        
    - name: copy go web service
      copy:
        src: files/django.service
        dest: /etc/systemd/system/
    
    - name: start django web
      systemd:
        name: django.service
        state: started
        enabled: yes

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted