- name: Install packages
  dnf:
    name: '{{ item }}'
    state: present
  loop:
    - epel-release
    - postgresql-server
    - postgresql
    - https://github.com/cybertec-postgresql/patroni-packaging/releases/download/1.6.5-1/patroni-1.6.5-1.rhel7.x86_64.rpm
    - http://mirror.centos.org/centos/7/extras/x86_64/Packages/etcd-3.3.11-2.el7.centos.x86_64.rpm

- name: Copy etcd.conf
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  notify: restart etcd
  
- name: Config patrony
  template:
    src: postgresql.yml.j2
    dest: /opt/app/patroni/etc/postgresql.yml
  notify: restart patroni

- name: start patroni
  systemd:
    name: patroni
    state: started
    enabled: yes    