all:
  children:
    webservers:
#    clients:


webservers:
  hosts:
    webserver1:
      ansible_host: 192.168.10.2
      ansible_ssh_private_key_file: .vagrant/machines/webserver1/virtualbox/private_key
    webserver2:
      ansible_host: 192.168.10.3
      ansible_ssh_private_key_file: .vagrant/machines/webserver2/virtualbox/private_key

logservers:
  hosts:
    logserver:
      ansible_host: 192.168.10.4
      ansible_ssh_private_key_file: .vagrant/machines/logserver/virtualbox/private_key