all:
  children:
    webservers:
    clients:
    dbs:
    dbproxies:
    firewalls:  

webservers:
  hosts:
    webserver1:
      ansible_host: 127.0.0.1
      ansible_port: 3002
      ansible_ssh_private_key_file: .vagrant/machines/webserver1/virtualbox/private_key
    webserver2:
      ansible_host: 127.0.0.1
      ansible_port: 3003
      ansible_ssh_private_key_file: .vagrant/machines/webserver2/virtualbox/private_key

logservers:
  hosts:
    logserver:
      ansible_host: 127.0.0.1
      ansible_port: 3004
      ansible_ssh_private_key_file: .vagrant/machines/logserver/virtualbox/private_key
      
webproxies:
  hosts:
    webproxy:
      ansible_host: 127.0.0.1
      ansible_port: 3005
      ansible_ssh_private_key_file: .vagrant/machines/webproxy/virtualbox/private_key
      
dbs:
  hosts:
    db1:
      ansible_host: 127.0.0.1
      ansible_port: 3006
      ansible_ssh_private_key_file: .vagrant/machines/db1/virtualbox/private_key
    db2:
      ansible_host: 127.0.0.1
      ansible_port: 3007
      ansible_ssh_private_key_file: .vagrant/machines/db2/virtualbox/private_key

dbproxies:
  hosts:
    dbproxy:
      ansible_host: 127.0.0.1
      ansible_port: 3008
      ansible_ssh_private_key_file: .vagrant/machines/dbproxy/virtualbox/private_key

firewalls:
  hosts:
    firewall:
      ansible_host: 127.0.0.1
      ansible_port: 3001
      ansible_ssh_private_key_file: .vagrant/machines/firewall/virtualbox/private_key