all:
  children:
    webservers:
    clients:
    dbs:
    dbproxies:
    firewalls:  

webservers:
  hosts:
    webserver1:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_private_key_file: .vagrant/machines/webserver1/virtualbox/private_key
    webserver2:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_ssh_private_key_file: .vagrant/machines/webserver2/virtualbox/private_key

logservers:
  hosts:
    logserver:
      ansible_host: 127.0.0.1
      ansible_port: 2201
      ansible_ssh_private_key_file: .vagrant/machines/logserver/virtualbox/private_key
      
webproxies:
  hosts:
    webproxy:
      ansible_host: 127.0.0.1
      ansible_port: 2202
      ansible_ssh_private_key_file: .vagrant/machines/webproxy/virtualbox/private_key
      
dbs:
  hosts:
    db1:
      ansible_host: 127.0.0.1
      ansible_port: 2203
      ansible_ssh_private_key_file: .vagrant/machines/db1/virtualbox/private_key
    db2:
      ansible_host: 127.0.0.1
      ansible_port: 2204
      ansible_ssh_private_key_file: .vagrant/machines/db2/virtualbox/private_key

dbproxies:
  hosts:
    dbproxy:
      ansible_host: 127.0.0.1
      ansible_port: 2205
      ansible_ssh_private_key_file: .vagrant/machines/dbproxy/virtualbox/private_key

firewalls:
  hosts:
    firewall:
      ansible_host: 127.0.0.1
      ansible_port: 2206
      ansible_ssh_private_key_file: .vagrant/machines/firewall/virtualbox/private_key