---
- name: Prepare client tasks
  hosts: ovpn-client
  become: true
  tasks:
    - name: Copy client keys
      copy:
        src: files/{{ item }}
        dest: /etc/openvpn/
      loop:
        - ca.crt
        - client.crt
        - client.key
    - name: Config client
      template:
        src: ras-client.conf.j2
        dest: /etc/openvpn/client.conf
      notify:
        - stop openvpn server
        - restart openvpn client
  handlers:
    - name: stop openvpn server
      systemd:
        name: openvpn@server
        state: stopped
        enabled: no
    - name: restart openvpn client
      systemd:
        name: openvpn@client
        state: restarted
        enabled: yes    