---
- name: Setup web
  hosts: centralServer
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: '{{item}}'          
        state: present
      loop:
        - epel-release
        - nginx
      notify: restart nginx
  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes