all:
  children:
    servers:
    workstations:

servers:
  hosts:
    ipaserver:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_private_key_file: .vagrant/machines/ipaserver/virtualbox/private_key

workstations:
  hosts:
    ws1:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_ssh_private_key_file: .vagrant/machines/ws1/virtualbox/private_key

    ws2:
      ansible_host: 127.0.0.1
      ansible_port: 2201
      ansible_ssh_private_key_file: .vagrant/machines/ws2/virtualbox/private_key