all:
  hosts:
    master:
      ansible_host: 192.168.10.10
#      ansible_port: 2222
      ansible_ssh_private_key_file: .vagrant/machines/master/virtualbox/private_key

    slave:
      ansible_host: 192.168.10.20
#      ansible_port: 2200
      ansible_ssh_private_key_file: .vagrant/machines/slave/virtualbox/private_key

    backup:
      ansible_host: 192.168.10.30
#      ansible_port: 2201
      ansible_ssh_private_key_file: .vagrant/machines/backup/virtualbox/private_key